package generator

const _baseTemplate = `
// Code generated by protoc-gen-yarpc-go
// source: {{.Filename}}
// DO NOT EDIT!

package {{.Package}}

{{if .Services -}}
import (
  {{range .Imports -}}{{printf "%q\n" .}}{{end -}}
)
{{end -}}

{{template "client" . -}}
{{template "server" . -}}
`
