package template

// Base represents the base template.
const Base = `
// Code generated by protoc-gen-yarpc-go
// source: {{.Filename}}
// DO NOT EDIT!

package {{.Package}}

{{if .Services -}}
import (
  {{range $i := .Imports -}}{{$i | printf "%s\n"}}{{end -}}
)
{{end -}}

{{template "client" -}}
{{template "server" -}}
`
