// Code generated by protoc-gen-yarpc-go
// source: key_value.proto
// DO NOT EDIT!

package keyvalue

import (
	context "context"
	proto "github.com/gogo/protobuf/proto"
	fx "go.uber.org/fx"
	yarpc "go.uber.org/yarpc/v2/yarpc"
	yarpcprotobuf "go.uber.org/yarpc/v2/yarpcprotobuf"
	ioutil "io/ioutil"
)

// KeyValueClient is the KeyValue service's client interface.
type KeyValueClient interface {
	Foo(
		context.Context,
		*GetRequest,
		...yarpc.CallOption,
	) (*GetResponse, error)
	Bar(
		context.Context,
		...yarpc.CallOption,
	) (KeyValueBarClientStream, error)
	Baz(
		context.Context,
		*GetRequest,
		...yarpc.CallOption,
	) (KeyValueBazClientStream, error)
	Qux(
		context.Context,
		...yarpc.CallOption,
	) (KeyValueQuxClientStream, error)
}

// KeyValueBarClientStream is a streaming interface used in the KeyValue}Client interface.
type KeyValueBarClientStream interface {
	Context() context.Context
	Send(*GetRequest, ...yarpc.StreamOption) error
	CloseAndRecv(...yarpc.StreamOption) (*GetResponse, error)
}

// KeyValueBazClientStream is a streaming interface used in the KeyValue}Client interface.
type KeyValueBazClientStream interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// KeyValueQuxClientStream is a streaming interface used in the KeyValue}Client interface.
type KeyValueQuxClientStream interface {
	Context() context.Context
	Send(*GetRequest, ...yarpc.StreamOption) error
	Recv(...yarpc.StreamOption) (*GetResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// KeyValueServer is the KeyValue service's server interface.
type KeyValueServer interface {
	Foo(
		context.Context,
		*GetRequest,
	) (*GetResponse, error)
	Bar(
		KeyValueBarServerStream,
	) (KeyValueBarServerStream, error)
	Baz(
		*GetRequest,
		KeyValueBazServerStream,
	) error
	Qux(
		KeyValueQuxServerStream,
	) error
}

// KeyValueBarServerStream is a streaming interface used in the KeyValue}Server interface.
type KeyValueBarServerStream interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetRequest, error)
}

// KeyValueBazServerStream is a streaming interface used in the KeyValue}Server interface.
type KeyValueBazServerStream interface {
	Context() context.Context
	Send(*GetResponse, ...yarpc.StreamOption) error
}

// KeyValueQuxServerStream is a streaming interface used in the KeyValue}Server interface.
type KeyValueQuxServerStream interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetRequest, error)
	Send(*GetResponse, ...yarpc.StreamOption) error
}

// BuildKeyValueProcedures constructs the YARPC procedures for the KeyValue service.
func BuildKeyValueProcedures(s KeyValueServer) []yarpc.Procedure {
	h := &_KeyValueHandler{server: s}
	return yarpcprotobuf.Procedures(
		yarpcprotobuf.ProceduresParams{
			Service: "KeyValue",
		},
	)
}

type _KeyValueHandler struct {
	server KeyValueServer
}
