// Code generated by protoc-gen-yarpc-go
// source: key_value.proto
// DO NOT EDIT!

package keyvalue

import (
	context "context"
	proto "github.com/gogo/protobuf/proto"
	fx "go.uber.org/fx"
	yarpc "go.uber.org/yarpc/v2/yarpc"
	yarpcprotobuf "go.uber.org/yarpc/v2/yarpcprotobuf"
)

// KeyValueClient is the KeyValue service's client interface.
type KeyValueClient interface {
	Foo(
		context.Context,
		*GetRequest,
		...yarpc.CallOption,
	) (*GetResponse, error)
	Bar(
		context.Context,
		...yarpc.CallOption,
	) (KeyValueBarClientStream, error)
	Baz(
		context.Context,
		*GetRequest,
		...yarpc.CallOption,
	) (KeyValueBazClientStream, error)
	Qux(
		context.Context,
		...yarpc.CallOption,
	) (KeyValueQuxClientStream, error)
}

// KeyValueBarClientStream is a streaming interface used in the KeyValue}Client interface.
type KeyValueBarClientStream interface {
	Context() context.Context
	Send(*GetRequest, ...yarpc.StreamOption) error
	CloseAndRecv(...yarpc.StreamOption) (*GetResponse, error)
}

// KeyValueBazClientStream is a streaming interface used in the KeyValue}Client interface.
type KeyValueBazClientStream interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// KeyValueQuxClientStream is a streaming interface used in the KeyValue}Client interface.
type KeyValueQuxClientStream interface {
	Context() context.Context
	Send(*GetRequest, ...yarpc.StreamOption) error
	Recv(...yarpc.StreamOption) (*GetResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// KeyValueServer is the KeyValue service's server interface.
type KeyValueServer interface {
	Foo(
		context.Context,
		*GetRequest,
	) (*GetResponse, error)
	Bar(
		KeyValueBarServerStream,
	) (KeyValueBarServerStream, error)
	Baz(
		*GetRequest,
		KeyValueBazServerStream,
	) error
	Qux(
		KeyValueQuxServerStream,
	) error
}

// KeyValueBarServerStream is a streaming interface used in the KeyValue}Server interface.
type KeyValueBarServerStream interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetRequest, error)
}

// KeyValueBazServerStream is a streaming interface used in the KeyValue}Server interface.
type KeyValueBazServerStream interface {
	Context() context.Context
	Send(*GetResponse, ...yarpc.StreamOption) error
}

// KeyValueQuxServerStream is a streaming interface used in the KeyValue}Server interface.
type KeyValueQuxServerStream interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetRequest, error)
	Send(*GetResponse, ...yarpc.StreamOption) error
}

type _KeyValueHandler struct {
	server KeyValueServer
}

// BuildKeyValueProcedures constructs the YARPC procedures for the KeyValue service.
func BuildKeyValueProcedures(s KeyValueServer) []yarpc.Procedure {
	h := &_KeyValueHandler{server: s}
	return yarpcprotobuf.Procedures(
		yarpcprotobuf.ProceduresParams{
			Service: "KeyValue",
			Unary: []yarpcprotobuf.UnaryProceduresParams{
				{
					MethodName: "Foo",
					Handler: yarpcprotobuf.NewUnaryHandler{
						yarpcprotobuf.UnaryHandlerParams{
							Handle: h.Foo,
							Create: newKeyValueFooRequest(),
						},
					},
				},
			},
			Stream: []yarpcprotobuf.StreamProceduresParams{
				{
					MethodName: "Bar",
					Handler: yarpcprotobuf.NewStreamHandler{
						yarpcprotobuf.StreamHandlerParams{
							Handle: h.Bar,
						},
					},
				},
				{
					MethodName: "Baz",
					Handler: yarpcprotobuf.NewStreamHandler{
						yarpcprotobuf.StreamHandlerParams{
							Handle: h.Baz,
						},
					},
				},
				{
					MethodName: "Qux",
					Handler: yarpcprotobuf.NewStreamHandler{
						yarpcprotobuf.StreamHandlerParams{
							Handle: h.Qux,
						},
					},
				},
			},
		},
	)
}

func newKeyValueFooRequest()  { return &GetRequest{} }
func newKeyValueFooResponse() { return &GetResponse{} }
func newKeyValueBarRequest()  { return &GetRequest{} }
func newKeyValueBarResponse() { return &GetResponse{} }
func newKeyValueBazRequest()  { return &GetRequest{} }
func newKeyValueBazResponse() { return &GetResponse{} }
func newKeyValueQuxRequest()  { return &GetRequest{} }
func newKeyValueQuxResponse() { return &GetResponse{} }

var (
	_emptyKeyValueFooRequest  = &GetRequest{}
	_emptyKeyValueFooResponse = &GetResponse{}
	_emptyKeyValueBarRequest  = &GetRequest{}
	_emptyKeyValueBarResponse = &GetResponse{}
	_emptyKeyValueBazRequest  = &GetRequest{}
	_emptyKeyValueBazResponse = &GetResponse{}
	_emptyKeyValueQuxRequest  = &GetRequest{}
	_emptyKeyValueQuxResponse = &GetResponse{}
)
