
// Code generated by protoc-gen-yarpc-go
// source: key_value.proto
// DO NOT EDIT!

package keyvaluepb

import (
  "context"
"io/ioutil"
"reflect"
"github.com/gogo/protobuf/proto"
"go.uber.org/fx"
"go.uber.org/v2/yarpc"
"go.uber.org/yarpc/v2/yarpcprotobuf"
)



type FooClient interface {

FooMethod(context.Context, FooRequest, ...yarpc.CallOption) (FooResponse, error)
BarMethod(context.Context, ...yarpc.CallOption) (FooBarResponseClient, error)
}

type BarMethodClient interface {
  Context() context.Context

  Send(BarRequest, ...yarpc.StreamOption) error
  Recv(...yarpc.StreamOption) (BarResponse, error)
  CloseSend(...yarpc.StreamOption) error
  }



type FooServer interface {

FooMethod(context.Context, FooRequest) (FooResponse, error)
BarMethod(FooBarMethodServer) (error)
}

type BarMethodServer interface {
  Context() context.Context

  Recv(...yarpc.StreamOption) (BarRequest, error)
  Send(BarResponse, ...yarpc.StreamOption) error
  }
