// Code generated by protoc-gen-yarpc-go
// source: key_value.proto
// DO NOT EDIT!

package keyvalue

import (
	context "context"
	proto "github.com/gogo/protobuf/proto"
	fx "go.uber.org/fx"
	yarpc "go.uber.org/yarpc/v2/yarpc"
	yarpcprotobuf "go.uber.org/yarpc/v2/yarpcprotobuf"
)

// KeyValueClient is the KeyValue service's client interface.
type KeyValueClient interface {
	Foo(
		context.Context,
		*GetRequest,
		...yarpc.CallOption,
	) (*GetResponse, error)
	Bar(
		context.Context,
		...yarpc.CallOption,
	) (KeyValueBarStreamClient, error)
	Baz(
		context.Context,
		*GetRequest,
		...yarpc.CallOption,
	) (KeyValueBazStreamClient, error)
	Qux(
		context.Context,
		...yarpc.CallOption,
	) (KeyValueQuxStreamClient, error)
}

// NewKeyValueClient builds a new YARPC client for the KeyValue service.
func NewKeyValueClient(c yarpc.Client, opts ...yarpcprotobuf.ClientOption) KeyValueClient {
	return &_KeyValueServer{stream: yarpcprotobuf.NewStreamClient(c, "keyvalue.KeyValue", opts...)}
}

type _KeyValueClient struct {
	stream yarpcprotobuf.StreamClient
}

func (c *_KeyValueClient) Foo(ctx context.Context, req *GetRequest, opts ...yarpc.CallOption) (*GetResponse, error) {
	msg, err := c.stream.Call(ctx, "Foo", req, newKeyValueFooResponse, opts...)
	if err != nil {
		return nil, err
	}
	res, ok := msg.(*GetResponse)
	if !ok {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueFooResponse, res)
	}
	return res, nil
}

func (c *_KeyValueClient) Bar(ctx context.Context, opts ...yarpc.CallOption) (KeyValueBarStreamClient, error) {
	s, err := c.stream.CallStream(ctx, "Bar", opts...)
	if err != nil {
		return err
	}
	return &_KeyValueBarStreamClient{stream: s}, nil
}

func (c *_KeyValueClient) Baz(ctx context.Context, req *GetRequest, opts ...yarpc.CallOption) (KeyValueBazStreamClient, error) {
	s, err := c.stream.CallStream(ctx, "Baz", opts...)
	if err != nil {
		return err
	}
	if err := s.Send(req); err != nil {
		return nil, err
	}
	return &_KeyValueBazStreamClient{stream: s}, nil
}

func (c *_KeyValueClient) Qux(ctx context.Context, opts ...yarpc.CallOption) (KeyValueQuxStreamClient, error) {
	s, err := c.stream.CallStream(ctx, "Qux", opts...)
	if err != nil {
		return nil, err
	}
	return &_KeyValueQuxStreamClient{stream: s}, nil
}

// KeyValueBarStreamClient is a streaming interface used in the KeyValueClient interface.
type KeyValueBarStreamClient interface {
	Context() context.Context
	Send(*GetRequest, ...yarpc.StreamOption) error
	CloseAndRecv(...yarpc.StreamOption) (*GetResponse, error)
}

// KeyValueBazStreamClient is a streaming interface used in the KeyValueClient interface.
type KeyValueBazStreamClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// KeyValueQuxStreamClient is a streaming interface used in the KeyValueClient interface.
type KeyValueQuxStreamClient interface {
	Context() context.Context
	Send(*GetRequest, ...yarpc.StreamOption) error
	Recv(...yarpc.StreamOption) (*GetResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

type _KeyValueBarStreamClient struct {
	stream *yarpcprotobuf.StreamClient
}

func (c *_KeyValueBarStreamClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_KeyValueBarStreamClient) Send(req *GetRequest, opts ...yarpc.StreamOption) error {
	return c.stream.Send(req, opts...)
}

func (c *_KeyValueBarStreamClient) CloseAndRecv(opts ...yarpc.StreamOption) (*GetRequest, error) {
	if err := c.stream.Close(opts...); err != nil {
		return nil, err
	}
	msg, err := c.stream.Receive(newKeyValueBarResponse, opts...)
	if err != nil {
		return nil, err
	}
	res, ok := msg.(*GetResponse)
	if !ok {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueBarResponse, msg)
	}
	return res, err
}

type _KeyValueBazStreamClient struct {
	stream *yarpcprotobuf.StreamClient
}

func (c *_KeyValueBazStreamClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_KeyValueBazStreamClient) Recv(opts ...yarpc.StreamOption) (*GetResponse, error) {
	msg, err := c.stream.Receive(newKeyValueBazResponse, opts...)
	if err != nil {
		return nil, err
	}
	res, ok := msg.(*GetResponse)
	if !ok {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueBazResponse, msg)
	}
	return res, nil
}

func (c *_KeyValueBazStreamClient) CloseSend(opts ...yarpc.StreamOption) error {
	return c.stream.Close(opts...)
}

type _KeyValueQuxStreamClient struct {
	stream *yarpcprotobuf.StreamClient
}

func (c *_KeyValueQuxStreamClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_KeyValueQuxStreamClient) Send(req *GetRequest, opts ...yarpc.StreamOption) error {
	return c.stream.Send(req, opts...)
}

func (c *_KeyValueQuxStreamClient) Recv(opts ...yarpc.StreamOption) (*GetResponse, error) {
	msg, err := c.stream.Receive(newKeyValueQuxResponse, opts...)
	if err != nil {
		return nil, err
	}
	res, ok := msg.(*GetResponse)
	if !ok {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueQuxResponse, msg)
	}
	return res, nil
}

func (c *_KeyValueQuxStreamClient) CloseSend(opts ...yarpc.StreamOption) error {
	return c.stream.Close(opts...)
}

// KeyValueServer is the KeyValue service's server interface.
type KeyValueServer interface {
	Foo(
		context.Context,
		*GetRequest,
	) (*GetResponse, error)
	Bar(
		KeyValueBarStreamServer,
	) (KeyValueBarStreamServer, error)
	Baz(
		*GetRequest,
		KeyValueBazStreamServer,
	) error
	Qux(
		KeyValueQuxStreamServer,
	) error
}

// BuildKeyValueProcedures constructs the YARPC procedures for the KeyValue service.
func BuildKeyValueProcedures(s KeyValueServer) []yarpc.Procedure {
	h := &_KeyValueServer{server: s}
	return yarpcprotobuf.Procedures(
		yarpcprotobuf.ProceduresParams{
			Service: "keyvalue.KeyValue",
			Unary: []yarpcprotobuf.UnaryProceduresParams{
				{
					MethodName: "Foo",
					Handler: yarpcprotobuf.NewUnaryHandler{
						yarpcprotobuf.UnaryHandlerParams{
							Handle: h.Foo,
							Create: newKeyValueFooRequest(),
						},
					},
				},
			},
			Stream: []yarpcprotobuf.StreamProceduresParams{
				{
					MethodName: "Bar",
					Handler: yarpcprotobuf.NewStreamHandler{
						yarpcprotobuf.StreamHandlerParams{
							Handle: h.Bar,
						},
					},
				},
				{
					MethodName: "Baz",
					Handler: yarpcprotobuf.NewStreamHandler{
						yarpcprotobuf.StreamHandlerParams{
							Handle: h.Baz,
						},
					},
				},
				{
					MethodName: "Qux",
					Handler: yarpcprotobuf.NewStreamHandler{
						yarpcprotobuf.StreamHandlerParams{
							Handle: h.Qux,
						},
					},
				},
			},
		},
	)
}

type _KeyValueServer struct {
	server KeyValueServer
}

func (h *_KeyValueServer) Foo(ctx context.Context, m proto.Message) (proto.Message, error) {
	req, _ := m.(*GetRequest)
	if req == nil {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueFooRequest, m)
	}
	return h.server.Foo(ctx, req)
}

func (h *_KeyValueServer) Bar(s *yarpcprotobuf.StreamServer) error {
	res, err := h.server.Bar(&_KeyValueBarStreamServer{server: s})
	if err != nil {
		return err
	}
	return s.Send(res)
}

func (h *_KeyValueServer) Baz(s *yarpcprotobuf.StreamServer) error {
	recv, err := s.Receive(newKeyValueBazRequest)
	if err != nil {
		return err
	}
	req, _ := recv.(*GetRequest)
	if req == nil {
		return yarpcprotobuf.CastError(_emptyKeyValueBazRequest, recv)
	}
	return h.server.Baz(req, &_KeyValueBazStreamServer{server: s})
}

func (h *_KeyValueServer) Qux(s *yarpcprotobuf.StreamServer) error {
	return h.server.Qux(&_KeyValueQuxStreamServer{stream: s})
}

// KeyValueBarStreamServer is a streaming interface used in the KeyValueServer interface.
type KeyValueBarStreamServer interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetRequest, error)
}

// KeyValueBazStreamServer is a streaming interface used in the KeyValueServer interface.
type KeyValueBazStreamServer interface {
	Context() context.Context
	Send(*GetResponse, ...yarpc.StreamOption) error
}

// KeyValueQuxStreamServer is a streaming interface used in the KeyValueServer interface.
type KeyValueQuxStreamServer interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetRequest, error)
	Send(*GetResponse, ...yarpc.StreamOption) error
}

type _KeyValueBarStreamServer struct {
	stream *yarpcprotobuf.StreamServer
}

func (s *_KeyValueBarStreamServer) Context() context.Context {
	return s.stream.Context()
}

func (s *_KeyValueBarStreamServer) Recv(opts ...yarpc.StreamOption) (*GetRequest, error) {
	msg, err := s.stream.Receive(newKeyValueBarRequest, opts...)
	if err != nil {
		return nil, err
	}
	req, ok := msg.(*GetRequest)
	if !ok {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueBarRequest, msg)
	}
	return req, nil
}

type _KeyValueBazStreamServer struct {
	stream *yarpcprotobuf.StreamServer
}

func (s *_KeyValueBazStreamServer) Context() context.Context {
	return s.stream.Context()
}

func (s *_KeyValueBazStreamServer) Send(res *GetResponse, opts ...yarpc.StreamOption) error {
	return s.stream.Send(res, opts...)
}

type _KeyValueQuxStreamServer struct {
	stream *yarpcprotobuf.StreamServer
}

func (s *_KeyValueQuxStreamServer) Context() context.Context {
	return s.stream.Context()
}

func (s *_KeyValueQuxStreamServer) Recv(opts ...yarpc.StreamOption) (*GetRequest, error) {
	msg, err := s.stream.Receive(newKeyValueQuxRequest, opts...)
	if err != nil {
		return nil, err
	}
	req, ok := msg.(*GetRequest)
	if !ok {
		return nil, yarpcprotobuf.CastError(_emptyKeyValueQuxRequest, msg)
	}
	return req, nil
}

func (s *_KeyValueQuxStreamServer) Send(res *GetResponse, opts ...yarpc.StreamOption) error {
	return s.stream.Send(res, opts...)
}

// FxKeyValueClientParams defines the parameters
// required to provide a KeyValueClient into an
// Fx application.
type FxKeyValueClientParams struct {
	fx.In

	Client yarpc.Client
}

// FxKeyValueClientResult provides a KeyValueClient
// into an Fx application.
type FxKeyValueClientResult struct {
	fx.Out

	Client KeyValueClient
}

// NewFxKeyValueClient provides a KeyValueClient
// into an Fx application, using the given
// name for routing.
//
//  fx.Provide(
//    keyvalue.NewFxKeyValueClient("service-name"),
//    ...
//  )
// TODO(mensch): How will this work in v2?
func NewFxKeyValueClient(_ string, opts ...yarpcprotobuf.ClientOption) interface{} {
	return func(p FxKeyValueClientParams) FxKeyValueClientResult {
		return FxKeyValueClientResult{
			Client: NewFxKeyValueClient(p.Client, opts...),
		}
	}
}

// FxKeyValueServerParams defines the paramaters
// required to provide the KeyValueServer procedures
// into an Fx application.
type FxKeyValueServerParams struct {
	fx.In

	Server KeyValueServer
}

// FxKeyValueServerResult provides the KeyValueServer
// procedures into an Fx application.
type FxKeyValueServerResult struct {
	fx.Out

	Procedures []yarpc.Procedure `group:"yarpcfx"`
}

// NewFxKeyValueServer provides the KeyValueServer
// procedures to an Fx application. It expects
// a KeyValueServer to be present in the container.
//
//  fx.Provide(
//    keyvalue.NewFxKeyValueServer(),
//    ...
//  )
func NewFxKeyValueServer() interface{} {
	return func(p FxKeyValueServerParams) FxKeyValueServerResult {
		return FxKeyValueServerResult{
			Procedures: BuildKeyValueProcedures(p.Server),
		}
	}
}

func newKeyValueFooRequest()  { return &GetRequest{} }
func newKeyValueFooResponse() { return &GetResponse{} }
func newKeyValueBarRequest()  { return &GetRequest{} }
func newKeyValueBarResponse() { return &GetResponse{} }
func newKeyValueBazRequest()  { return &GetRequest{} }
func newKeyValueBazResponse() { return &GetResponse{} }
func newKeyValueQuxRequest()  { return &GetRequest{} }
func newKeyValueQuxResponse() { return &GetResponse{} }

var (
	_emptyKeyValueFooRequest  = &GetRequest{}
	_emptyKeyValueFooResponse = &GetResponse{}
	_emptyKeyValueBarRequest  = &GetRequest{}
	_emptyKeyValueBarResponse = &GetResponse{}
	_emptyKeyValueBazRequest  = &GetRequest{}
	_emptyKeyValueBazResponse = &GetResponse{}
	_emptyKeyValueQuxRequest  = &GetRequest{}
	_emptyKeyValueQuxResponse = &GetResponse{}
)
